### PR TITLE
pass extra arguments (#51)

### PR DESCRIPTION
**Pull request by lucas-mior**
- change cmdline options
- pass extras to NewPreviewer
- parse %pistol-extra[0-9]+% from config file
- note on README about extra args

adresses #51.
thanks for reviewing it.

### CODE REVIEW

**Comment by doronbehar** [comment]
Thanks a lot for the patch @lucas-mior ! I added tests and edited the documentation to explain the feature better as I had issues myself understanding it at first :). Could you please read the current version of the README in your branch? I'd like to add there an example usage for image previews that works for you currently.

Also, I noticed you use 2 different email addresses for committing changes - in general it'd be nice for you to add them both to your github account so that it'll be easy to trace you in GitHub blame.

**Comment by doronbehar** [comment]
The feature is explained here: https://github.com/lucas-mior/pistol/blob/master/README.adoc#passing-arbitrary-extra-arguments-to-commands

**Comment by lucas-mior** [comment]
Done.
As a side note, it might not be wise to use pistol as a fast previewer and then add a slow shell script on top of it.
In the future I shall reference a image previewer written in C that I'm working on.

**Comment by lucas-mior** [comment]
In the doc you added, you mention that one could pass up until 9 extra arguments,
which is not the case. Currently pistol will pass any argument matched with `%pistol-extra([0-9]+)%`.
I just don't know if you did that because it's more desirable to do the former (limit to 9)?
Feel free to change that :)

**Comment by doronbehar** [comment]
> In the doc you added, you mention that one could pass up until 9 extra arguments,
> which is not the case. Currently pistol will pass any argument matched with `%pistol-extra([0-9]+)%` (if such argument is passed to pistol).
> I just don't know if you did that because it's more desirable to do the former (limit to 9)?
> Feel free to change that :)

Did not intend to change / suggest changing that and I'm fine with having no limit. I misinterpreted what the code does.

> Done.

Thanks again :) If in the future, you'd have a more targeted script that does what `pv` does for images, it'd be nice to update the README to mention it.

**Review by doronbehar — APPROVED** [review]

**Pull request merged**
