### PR TITLE
Support fpath config keyword for match against file path

### PR DESCRIPTION
**Pull request by doronbehar**
Fixes https://github.com/doronbehar/pistol/issues/9 .

@smhmd could you please test this? You should be able to build `pistol` with:

```
git clone -b filepath-config-match https://github.com/doronbehar/pistol
cd pistol/cmd/pistol
go install
```

And use the following in your config:

```
fpath .*\.md bat --style=plain --paging=never --color=always %s
```

(That's what I tested).

Or for `mdcat`:

```
fpath .*\.md mdcat %s
```

(Untested).

### CODE REVIEW

**Comment by smhmd** [comment]
Is there a breaking change from the old syntax? some of them work, some of them don't.
[asciicast](https://asciinema.org/a/CI87iL4sqdvoNYdJVaJnsV0Pm)

Here's my pistolrc:
```fish
text/html w3m -T text/html -dump %s
text/* cat %s

application/* cat %s

audio/* mediainfo %s

video/* mediainfo %s

application/x-rar lsar %s
application/zip lsar %s

application/pdf pdftotext -l 10 -nopgbrk -q -- %s -
application/epub\+zip epub2txt -m --notext %s

image/vnd.djvu djvutxt %s

application/vnd.openxmlformats-officedocument.wordprocessingml.document doctotext %s
```
---

I tested `fpath .*\.md ....` with a bunch of markdown previewers, they all work perfectly.
But, what's the syntax exactly? you have a `.`, a wildcard `*`, then you are escaping another `.`, then the extension (`md`). 
From the keyword `fpath`, this supports different rules for different paths, no? Could you give an example?

**Comment by doronbehar** [comment]
> Is there a breaking change from the old syntax? some of them work, some of them don't.

Funny, can't reproduce, even with exactly your config. I think I've fixed those errors though by applying some changes. Could you check now? Also, if you continue to encounter errors, could you test it with `env PISTOL_DEBUG=1 pistol file > /dev/null` and paste the output?

> I tested fpath `.*\.md` .... with a bunch of markdown previewers, they all work perfectly.
But, what's the syntax exactly? you have a ., a wildcard *, then you are escaping another ., then the extension (md).

Yea that wasn't very intuitive :/ Sorry for being non-explanatory. I haven't documented yet this new syntax because I wanted to get your feedback, but roughly, it goes like this:

- 1st word is either a mime type or the special `fpath` keyword.
- If the 1st word is `fpath`, the 2nd word is a file path regex, meaning you can put any regex [this engine](https://golang.org/pkg/regexp/syntax) understands (just like mime type regex matching, see [this](https://github.com/doronbehar/pistol/blob/v0.0.3/README.md#a-note-on-regex-matching)). Currently, the string of the file path it is matched against is identical to the argument `pistol` gets.
- Mime types are tested for a match before file path regexes.

Note: The usage of the `\` and the `.` in `.*\.md`, is to make sure e.g the file `ablemd` won't be matched, I used : 
-  `.*` - to match any character what's so ever
- Then, an explicit `.` (hence the `\`).
- And then, `md`.

Now that I think about it, perhaps `.*\.md$` should have been used so `able.mdic` won't be matched.

> From the keyword fpath, this supports different rules for different paths, no? Could you give an example.

Yes, but full paths are not used, just the paths pistol gets in it's arguments. I can make it happen though, I think.

**Comment by smhmd** [comment]
Works great. 👍 
With proper documentation, only time will tell if there are any other bugs.

**Comment by doronbehar** [comment]
Thanks for the feedback @smhmd .

**Pull request merged**
